/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.LOOPER_gentsWear.view_panel;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import lk.ijse.LOOPER_gentsWear.controller.ManageItemController;
import lk.ijse.LOOPER_gentsWear.controller.ManagePlaceOrderController;
import lk.ijse.LOOPER_gentsWear.dto.ItemDTO;
import lk.ijse.LOOPER_gentsWear.dto.OrderDTO;
import lk.ijse.LOOPER_gentsWear.view.HomePage;
import lk.ijse.LOOPER_gentsWear.view.POS_Main_Cashier;


/**
 *
 * @author Sandun_CJ
 */
public class CustomerReturnPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public CustomerReturnPanel() {
        initComponents();
        loadAllOrderIDs();
        loadItemCodes();
        setDate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddToTable = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUnitprice = new javax.swing.JTextField();
        cmbItemCode = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        cmbInvoiceNo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 3));
        setPreferredSize(new java.awt.Dimension(1070, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/return.png"))); // NOI18N
        jLabel2.setText("Customer's Return..");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 50));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/Entypo_d83d(0)_32_6.png"))); // NOI18N
        jButton1.setText("Update Items");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 160, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/FontAwesome_f063(0)_32.png"))); // NOI18N
        jButton2.setText("Deduction");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 130, 30));

        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 110, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Sub Amount");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 80, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Return ID", "Invoice No", "Item Code", "Description", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 1010, 240));

        btnAddToTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAddToTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/Entypo_e70c(0)_32.png"))); // NOI18N
        btnAddToTable.setText("Add");
        btnAddToTable.setToolTipText("Add details to table");
        btnAddToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToTableActionPerformed(evt);
            }
        });
        add(btnAddToTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 100, 30));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 330, 30));

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 110, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Date");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 40, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Description");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 80, 30));

        txtDescription.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDescription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 110, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Reason");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 74, 30));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 90, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Item Code");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 80, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Amount");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 74, 30));

        txtUnitprice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUnitprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnitprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtUnitprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 90, 30));

        cmbItemCode.setEditable(true);
        cmbItemCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbItemCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemCodeItemStateChanged(evt);
            }
        });
        add(cmbItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 100, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Invoic No");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Unit Price");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 74, 30));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, 30));

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Quantity");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 74, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Return ID");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 74, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/back-button.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 60, 60));

        cmbInvoiceNo.setEditable(true);
        cmbInvoiceNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cmbInvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToTableActionPerformed

    }//GEN-LAST:event_btnAddToTableActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        HomePanel homePanel=new HomePanel();
        JPanel panel=HomePage.getMainPanel();
        panel.removeAll();
        homePanel.setSize(panel.getSize());
        panel.add(homePanel);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setSize(65,65);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setSize(60,60);
    }//GEN-LAST:event_btnBackMouseExited

    private void cmbItemCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemCodeItemStateChanged
        if (cmbItemCode.getSelectedIndex() != -1) {
            try {
                ItemDTO searchItem = ManageItemController.searchItem(cmbItemCode.getSelectedItem().toString());
                txtDescription.setText(searchItem.getDescription());
                txtUnitprice.setText(Integer.toString(searchItem.getQty()));
                

            } catch (Exception ex) {
                Logger.getLogger(CustomerReturnPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmbItemCodeItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToTable;
    private javax.swing.JLabel btnBack;
    private javax.swing.JComboBox<String> cmbInvoiceNo;
    private javax.swing.JComboBox<String> cmbItemCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtUnitprice;
    // End of variables declaration//GEN-END:variables

    private void loadAllOrderIDs() {
        try {
            List<OrderDTO> orders = ManagePlaceOrderController.getAllOrders();
            if(orders !=null){
                for (OrderDTO orderDTO : orders) {
                    cmbInvoiceNo.addItem(Integer.toString(orderDTO.getoID()));
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerReturnPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadItemCodes() {
        try {
            List<ItemDTO> items = ManageItemController.getAllItems();
            if(items!=null){
                for (ItemDTO itemDTO : items) {
                    cmbItemCode.addItem(itemDTO.getiCode());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerReturnPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("E dd-MM-yyyy");
        txtDate.setText(s.format(d));
    }
}
