/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.LOOPER_gentsWear.view_panel;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import lk.ijse.LOOPER_gentsWear.view.HomePage;

/**
 *
 * @author Sandun_CJ
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public HomePanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblCusReturn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSale = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSupReturn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/home.png"))); // NOI18N
        jLabel2.setText("HOME..");
        add(jLabel2);
        jLabel2.setBounds(0, 10, 170, 50);

        lblCusReturn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCusReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCusReturn.setText("Customer Return");
        lblCusReturn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblCusReturn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        lblCusReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCusReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCusReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCusReturnMouseExited(evt);
            }
        });
        add(lblCusReturn);
        lblCusReturn.setBounds(330, 80, 160, 180);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/CustReturn.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        add(jLabel6);
        jLabel6.setBounds(340, 90, 140, 140);

        lblSale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSale.setText("Sales");
        lblSale.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblSale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        lblSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaleMouseExited(evt);
            }
        });
        add(lblSale);
        lblSale.setBounds(60, 80, 160, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/sale.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(70, 90, 140, 140);

        lblSupReturn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSupReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupReturn.setText("Supplier Return");
        lblSupReturn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblSupReturn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        lblSupReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupReturnMouseExited(evt);
            }
        });
        add(lblSupReturn);
        lblSupReturn.setBounds(600, 80, 160, 180);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/SupplierReturn.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(610, 90, 140, 140);

        lblAbout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbout.setText("About");
        lblAbout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblAbout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAboutMouseExited(evt);
            }
        });
        add(lblAbout);
        lblAbout.setBounds(850, 80, 160, 180);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/About.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(860, 90, 140, 140);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/wellcome(4).png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 490, 280));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/1.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 220, 87));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/3.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 171, 35));

        add(jPanel1);
        jPanel1.setBounds(60, 280, 950, 280);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 3));
        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCusReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusReturnMouseClicked
        CustomerReturnPanel customerReturnPanel = new CustomerReturnPanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        customerReturnPanel.setSize(middlePanel.getSize());
        middlePanel.add(customerReturnPanel);
        middlePanel.revalidate();

        middlePanel.repaint();
    }//GEN-LAST:event_lblCusReturnMouseClicked

    private void lblCusReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusReturnMouseEntered
        lblCusReturn.setBorder(new LineBorder(new Color(0, 102, 255), 3));
    }//GEN-LAST:event_lblCusReturnMouseEntered

    private void lblCusReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCusReturnMouseExited
        lblCusReturn.setBorder(new LineBorder(new Color(204, 204, 204), 3));
    }//GEN-LAST:event_lblCusReturnMouseExited

    private void lblSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaleMouseClicked

    private void lblSaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaleMouseEntered
        lblSale.setBorder(new LineBorder(new Color(0, 102, 255), 3));
    }//GEN-LAST:event_lblSaleMouseEntered

    private void lblSaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaleMouseExited
        lblSale.setBorder(new LineBorder(new Color(204, 204, 204), 3));
    }//GEN-LAST:event_lblSaleMouseExited

    private void lblSupReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupReturnMouseClicked
        SupplierReturnPanel supplierReturnPanel = new SupplierReturnPanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        supplierReturnPanel.setSize(middlePanel.getSize());
        middlePanel.add(supplierReturnPanel);
        middlePanel.repaint();
        middlePanel.revalidate();
    }//GEN-LAST:event_lblSupReturnMouseClicked

    private void lblSupReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupReturnMouseEntered
        lblSupReturn.setBorder(new LineBorder(new Color(0, 102, 255), 3));
    }//GEN-LAST:event_lblSupReturnMouseEntered

    private void lblSupReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupReturnMouseExited
        lblSupReturn.setBorder(new LineBorder(new Color(204, 204, 204), 3));
    }//GEN-LAST:event_lblSupReturnMouseExited

    private void lblAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseClicked

        AboutPanel aboutPanel = new AboutPanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        aboutPanel.setSize(middlePanel.getSize());
        middlePanel.add(aboutPanel);
        middlePanel.repaint();
        middlePanel.revalidate();
    }//GEN-LAST:event_lblAboutMouseClicked

    private void lblAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseEntered
        lblAbout.setBorder(new LineBorder(new Color(0, 102, 255), 3));
    }//GEN-LAST:event_lblAboutMouseEntered

    private void lblAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseExited
        lblAbout.setBorder(new LineBorder(new Color(204, 204, 204), 3));
    }//GEN-LAST:event_lblAboutMouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblCusReturn;
    private javax.swing.JLabel lblSale;
    private javax.swing.JLabel lblSupReturn;
    // End of variables declaration//GEN-END:variables

}
