/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.LOOPER_gentsWear.view_panel;

import java.awt.Color;
import static java.awt.image.ImageObserver.ERROR;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import lk.ijse.LOOPER_gentsWear.view.HomePage;

/**
 *
 * @author Sandun_CJ
 */
public class SettingPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public SettingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblCashier = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/setting.png"))); // NOI18N
        jLabel2.setText("SETTING..");
        add(jLabel2);
        jLabel2.setBounds(0, 10, 190, 50);

        lblCashier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCashier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCashier.setText("Cashier's Setting");
        lblCashier.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblCashier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        lblCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCashierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCashierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCashierMouseExited(evt);
            }
        });
        add(lblCashier);
        lblCashier.setBounds(60, 100, 160, 190);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/Cashi.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        add(jLabel5);
        jLabel5.setBounds(70, 110, 145, 130);

        lblEmployee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployee.setText("Employee");
        lblEmployee.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        lblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseExited(evt);
            }
        });
        add(lblEmployee);
        lblEmployee.setBounds(540, 100, 160, 190);

        lblAdmin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmin.setText("Admin's Setting");
        lblAdmin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        lblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdminMouseExited(evt);
            }
        });
        add(lblAdmin);
        lblAdmin.setBounds(300, 100, 160, 190);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/Admin.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(310, 110, 140, 140);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/emp.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(570, 120, 110, 130);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 3));
        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lblCashierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMouseEntered
        lblCashier.setBorder(new LineBorder(new Color(0, 102, 205), 2));
    }//GEN-LAST:event_lblCashierMouseEntered

    private void lblCashierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMouseExited
        lblCashier.setBorder(new LineBorder(new Color(204, 204, 204), 2));
    }//GEN-LAST:event_lblCashierMouseExited

    private void lblCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMouseClicked
        CashierSettingPanel cashierSettingPanel = new CashierSettingPanel();
        JPanel panel = HomePage.getMainPanel();
        panel.removeAll();
        cashierSettingPanel.setSize(780, 500);
        panel.add(cashierSettingPanel);
        panel.revalidate();
        panel.repaint();

    }//GEN-LAST:event_lblCashierMouseClicked

    private void lblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEmployeeMouseClicked

    private void lblEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseEntered
        lblEmployee.setBorder(new LineBorder(new Color(0, 102, 205), 2));
    }//GEN-LAST:event_lblEmployeeMouseEntered

    private void lblEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseExited
        lblEmployee.setBorder(new LineBorder(new Color(204, 204, 204), 2));
    }//GEN-LAST:event_lblEmployeeMouseExited

    private void lblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseClicked
        AdminSettingPanel adminSettingPanel = new AdminSettingPanel();
        JPanel panel = HomePage.getMainPanel();
        panel.removeAll();
        adminSettingPanel.setSize(780, 500);
        panel.add(adminSettingPanel);
        panel.revalidate();
        panel.repaint();

    }//GEN-LAST:event_lblAdminMouseClicked

    private void lblAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseEntered
        lblAdmin.setBorder(new LineBorder(new Color(0, 102, 205), 2));
    }//GEN-LAST:event_lblAdminMouseEntered

    private void lblAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseExited
        lblAdmin.setBorder(new LineBorder(new Color(204, 204, 204), 2));
    }//GEN-LAST:event_lblAdminMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblCashier;
    private javax.swing.JLabel lblEmployee;
    // End of variables declaration//GEN-END:variables
}
