/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.LOOPER_gentsWear.view_panel;

import com.sun.javafx.image.impl.IntArgb;
import java.awt.Color;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.LOOPER_gentsWear.common.Validation;
import lk.ijse.LOOPER_gentsWear.controller.ManageItemController;
import lk.ijse.LOOPER_gentsWear.controller.ManageSupplierController;
import lk.ijse.LOOPER_gentsWear.dto.ItemDTO;
import lk.ijse.LOOPER_gentsWear.dto.SupplierDTO;
import lk.ijse.LOOPER_gentsWear.observer.Observer;
import lk.ijse.LOOPER_gentsWear.view.HomePage;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Sandun_CJ
 */
public class SupplierPanel extends javax.swing.JPanel implements Observer {

    private boolean update = false;
    private String reservedSup_Code = "";
    private boolean isID;
    private boolean isName;

    /**
     * Creates new form NewJPanel
     */
    public SupplierPanel() {
        initComponents();

        loadAllSuppliers();
        AutoCompleteDecorator.decorate(cmbSupplier);
        scrTbl.getViewport().setBackground(Color.WHITE);

        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageSupplierController.getSubject().registerObserver(this);
        } catch (RemoteException ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblSupplier.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (tblSupplier.getSelectedRow() == -1) {
                    btnDelete.setEnabled(true);
                    btnUpdate.setEnabled(true);
                    update = false;
                    return;
                }

                try {
                    if (reservedSup_Code == "") {
                        ManageItemController.releaseItem(reservedSup_Code);
                    }

                    reservedSup_Code = tblSupplier.getValueAt(tblSupplier.getSelectedRow(), 0).toString();
                    boolean reservSupplier = ManageSupplierController.reservSupplier(reservedSup_Code);

                    if (reservSupplier) {
                        update = true;
                        int row = tblSupplier.getSelectedRow();

                        txtSupplierID.setText(tblSupplier.getValueAt(row, 0).toString());
                        txtSupplierName.setText(tblSupplier.getValueAt(row, 1).toString());
                        txtSupplierTele.setText(tblSupplier.getValueAt(row, 2).toString());
                        txtSupplierNIC.setText(tblSupplier.getValueAt(row, 3).toString());
                        txtCompanyName.setText(tblSupplier.getValueAt(row, 4).toString());
                        txtCompanyAddress.setText(tblSupplier.getValueAt(row, 5).toString());

                    } else {
                        update = false;
                        JOptionPane.showMessageDialog(SupplierPanel.this, "Supplier has been already reserved");
                        tblSupplier.clearSelection();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtSupplierID = new javax.swing.JTextField();
        btnNewItemCategory1 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtSupplierTele = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtSupplierNIC = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtCompanyAddress = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        btnID = new javax.swing.JButton();
        btnName = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        scrTbl = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtCurrentSupplier = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        lblSupplierPayment = new javax.swing.JLabel();
        lblSupplierOrders = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1070, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/supplier.png"))); // NOI18N
        jLabel2.setText("SUPPLIER..");
        add(jLabel2);
        jLabel2.setBounds(10, 10, 190, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Supplier ID");
        add(jLabel5);
        jLabel5.setBounds(50, 280, 100, 30);
        add(jSeparator2);
        jSeparator2.setBounds(180, 300, 150, 10);

        txtSupplierID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSupplierID.setBorder(null);
        txtSupplierID.setDragEnabled(true);
        add(txtSupplierID);
        txtSupplierID.setBounds(180, 270, 150, 30);

        btnNewItemCategory1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnNewItemCategory1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/add.png"))); // NOI18N
        btnNewItemCategory1.setMnemonic('N');
        btnNewItemCategory1.setText("New Supplier");
        btnNewItemCategory1.setToolTipText("Click to add new subject");
        btnNewItemCategory1.setFocusPainted(false);
        btnNewItemCategory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewItemCategory1ActionPerformed(evt);
            }
        });
        add(btnNewItemCategory1);
        btnNewItemCategory1.setBounds(40, 230, 140, 30);

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setToolTipText("Clikc to save changes");
        btnSave.setFocusPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(300, 520, 90, 33);

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(60, 520, 110, 33);

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/update.png"))); // NOI18N
        btnUpdate.setText("Modify");
        btnUpdate.setToolTipText("Clikc to save changes");
        btnUpdate.setFocusPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(180, 520, 110, 33);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Supplier Name");
        add(jLabel6);
        jLabel6.setBounds(50, 320, 100, 30);

        txtSupplierName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSupplierName.setBorder(null);
        txtSupplierName.setDragEnabled(true);
        txtSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNameActionPerformed(evt);
            }
        });
        add(txtSupplierName);
        txtSupplierName.setBounds(180, 310, 150, 30);
        add(jSeparator3);
        jSeparator3.setBounds(180, 340, 150, 10);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Contact No");
        add(jLabel7);
        jLabel7.setBounds(50, 360, 100, 30);

        txtSupplierTele.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSupplierTele.setBorder(null);
        txtSupplierTele.setDragEnabled(true);
        txtSupplierTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierTeleActionPerformed(evt);
            }
        });
        add(txtSupplierTele);
        txtSupplierTele.setBounds(180, 350, 150, 30);
        add(jSeparator4);
        jSeparator4.setBounds(180, 380, 150, 10);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Supplier NIC");
        add(jLabel8);
        jLabel8.setBounds(50, 400, 100, 30);

        txtSupplierNIC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSupplierNIC.setBorder(null);
        txtSupplierNIC.setDragEnabled(true);
        txtSupplierNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNICActionPerformed(evt);
            }
        });
        add(txtSupplierNIC);
        txtSupplierNIC.setBounds(180, 390, 150, 30);
        add(jSeparator5);
        jSeparator5.setBounds(180, 420, 150, 10);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Company Name");
        add(jLabel9);
        jLabel9.setBounds(50, 440, 100, 30);

        txtCompanyName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCompanyName.setBorder(null);
        txtCompanyName.setDragEnabled(true);
        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });
        add(txtCompanyName);
        txtCompanyName.setBounds(180, 430, 150, 30);
        add(jSeparator6);
        jSeparator6.setBounds(180, 460, 150, 10);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Company Address");
        add(jLabel11);
        jLabel11.setBounds(50, 480, 110, 30);

        txtCompanyAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCompanyAddress.setBorder(null);
        txtCompanyAddress.setDragEnabled(true);
        txtCompanyAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyAddressActionPerformed(evt);
            }
        });
        add(txtCompanyAddress);
        txtCompanyAddress.setBounds(180, 470, 150, 30);
        add(jSeparator8);
        jSeparator8.setBounds(180, 500, 150, 10);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Supplier");
        add(jLabel12);
        jLabel12.setBounds(50, 100, 70, 30);

        btnID.setText("ID");
        btnID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIDMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIDMouseEntered(evt);
            }
        });
        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });
        add(btnID);
        btnID.setBounds(250, 120, 90, 30);

        btnName.setText("Name");
        btnName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNameMouseExited(evt);
            }
        });
        btnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameActionPerformed(evt);
            }
        });
        add(btnName);
        btnName.setBounds(250, 160, 90, 30);

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Sort By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(230, 90, 130, 110);

        cmbSupplier.setEditable(true);
        cmbSupplier.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbSupplier.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSupplierItemStateChanged(evt);
            }
        });
        cmbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupplierActionPerformed(evt);
            }
        });
        add(cmbSupplier);
        cmbSupplier.setBounds(50, 140, 150, 30);

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Supplier Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(30, 210, 380, 350);

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Search By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(30, 70, 380, 140);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Contact No", "Supplier NIC", "Company Name", "Cmp Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrTbl.setViewportView(tblSupplier);
        if (tblSupplier.getColumnModel().getColumnCount() > 0) {
            tblSupplier.getColumnModel().getColumn(0).setResizable(false);
            tblSupplier.getColumnModel().getColumn(1).setResizable(false);
            tblSupplier.getColumnModel().getColumn(2).setResizable(false);
            tblSupplier.getColumnModel().getColumn(3).setResizable(false);
            tblSupplier.getColumnModel().getColumn(4).setResizable(false);
            tblSupplier.getColumnModel().getColumn(5).setResizable(false);
        }

        add(scrTbl);
        scrTbl.setBounds(420, 80, 630, 310);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Total Current Suppliers");
        add(jLabel13);
        jLabel13.setBounds(450, 410, 140, 30);

        txtCurrentSupplier.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCurrentSupplier.setBorder(null);
        txtCurrentSupplier.setDragEnabled(true);
        add(txtCurrentSupplier);
        txtCurrentSupplier.setBounds(600, 400, 50, 30);
        add(jSeparator9);
        jSeparator9.setBounds(600, 430, 50, 10);

        lblSupplierPayment.setBackground(new java.awt.Color(204, 204, 255));
        lblSupplierPayment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSupplierPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/supplier Payment.png"))); // NOI18N
        lblSupplierPayment.setText("Supplier Payment");
        lblSupplierPayment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSupplierPayment.setOpaque(true);
        lblSupplierPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupplierPaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupplierPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupplierPaymentMouseExited(evt);
            }
        });
        add(lblSupplierPayment);
        lblSupplierPayment.setBounds(440, 500, 200, 50);

        lblSupplierOrders.setBackground(new java.awt.Color(204, 204, 255));
        lblSupplierOrders.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSupplierOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/SupplierOrder.png"))); // NOI18N
        lblSupplierOrders.setText("Supplier Order");
        lblSupplierOrders.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSupplierOrders.setOpaque(true);
        lblSupplierOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupplierOrdersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupplierOrdersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupplierOrdersMouseExited(evt);
            }
        });
        add(lblSupplierOrders);
        lblSupplierOrders.setBounds(860, 20, 170, 50);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 3));
        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewItemCategory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewItemCategory1ActionPerformed
        clearAllTextFields();
        txtSupplierID.requestFocusInWindow();
        tblSupplier.clearSelection();
    }//GEN-LAST:event_btnNewItemCategory1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        SupplierDTO supplier = new SupplierDTO(
                txtSupplierID.getText(),
                txtSupplierName.getText(),
                txtSupplierTele.getText(),
                txtSupplierNIC.getText(),
                txtCompanyName.getText(),
                txtCompanyAddress.getText()
        );
        try {
            boolean result = false;
            if (!update) {
                result = ManageSupplierController.addSupplier(supplier);
            }
            if (result) {
                JOptionPane.showMessageDialog(this, "Supplier has been Saved Successfull..");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Save the Supplier..");
            }

            ManageItemController.releaseItem(reservedSup_Code);
            reservedSup_Code = "";
            clearAllTextFields();
            tblSupplier.clearSelection();
            txtSupplierID.requestFocusInWindow();
            update = false;
        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadAllSuppliers();
        clearAllTextFields();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            boolean result = ManageSupplierController.deleteSupplier(txtSupplierID.getText());

            if (result) {
                JOptionPane.showMessageDialog(this, "Supplier has been Deleted Successfull..");
            } else {
                JOptionPane.showConfirmDialog(this, "Supplier Deleted Fail..");
            }

            ManageItemController.releaseItem(reservedSup_Code);
            reservedSup_Code = "";
            clearAllTextFields();
            tblSupplier.clearSelection();
            txtSupplierID.requestFocusInWindow();
            update = false;

        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadAllSuppliers();
        clearAllTextFields();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        SupplierDTO supplier = new SupplierDTO(
                txtSupplierID.getText(),
                txtSupplierName.getText(),
                txtSupplierTele.getText(),
                txtSupplierNIC.getText(),
                txtCompanyName.getText(),
                txtCompanyAddress.getText()
        );
        try {
            boolean result = true;
            if (update) {
                result = ManageSupplierController.updateSupplier(supplier);
            }

            if (!result) {
                JOptionPane.showMessageDialog(this, "Update successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed Update");
            }

            ManageItemController.releaseItem(reservedSup_Code);
            reservedSup_Code = "";
            clearAllTextFields();
            tblSupplier.clearSelection();
            txtSupplierID.requestFocusInWindow();
            update = false;

            loadAllSuppliers();
            clearAllTextFields();
        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed
        isID = true;
        try {
            List<SupplierDTO> supplierIdList = ManageSupplierController.getAllSuppliers();
            cmbSupplier.removeAllItems();
            for (SupplierDTO supplierId : supplierIdList) {
                cmbSupplier.addItem(supplierId.getSup_id());
            }
        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadAllSuppliers();
    }//GEN-LAST:event_btnIDActionPerformed

    private void btnIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIDMouseClicked

    private void btnIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIDMouseEntered
        btnID.setSize(93, 33);
    }//GEN-LAST:event_btnIDMouseEntered

    private void btnNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNameMouseEntered
        btnName.setSize(93, 33);
    }//GEN-LAST:event_btnNameMouseEntered

    private void btnIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIDMouseExited
        btnID.setSize(90, 30);
    }//GEN-LAST:event_btnIDMouseExited

    private void btnNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNameMouseExited
        btnName.setSize(90, 30);
    }//GEN-LAST:event_btnNameMouseExited

    private void btnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameActionPerformed
        isName = true;
        try {
            List<SupplierDTO> customerIdList = ManageSupplierController.getAllSuppliers();
            cmbSupplier.removeAllItems();
            for (SupplierDTO customerId : customerIdList) {
                cmbSupplier.addItem(customerId.getSup_name());
            }
        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadAllSuppliers();
    }//GEN-LAST:event_btnNameActionPerformed

    private void cmbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSupplierActionPerformed

    }//GEN-LAST:event_cmbSupplierActionPerformed

    private void cmbSupplierItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSupplierItemStateChanged

        String selectedItem = (String) cmbSupplier.getSelectedItem();
        SupplierDTO supplierDTO = new SupplierDTO();
        supplierDTO.setSup_id(selectedItem);
        supplierDTO.setSup_name(selectedItem);

        if (isID) {

            try {
                SupplierDTO searchedSupplier = ManageSupplierController.searchSupplierbyId((String) cmbSupplier.getSelectedItem());
                txtSupplierID.setText(searchedSupplier.getSup_id());
                txtSupplierName.setText(searchedSupplier.getSup_name());
                txtSupplierTele.setText(searchedSupplier.getTel_no());
                txtSupplierNIC.setText((searchedSupplier.getNic()));
                txtCompanyName.setText(searchedSupplier.getCompany_name());
                txtCompanyAddress.setText(searchedSupplier.getCompany_address());
            } catch (Exception ex) {
                Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

        }

        if (isName) {

            try {
                SupplierDTO searchedSupplier = ManageSupplierController.searchSupplierbyName((String) cmbSupplier.getSelectedItem());
                txtSupplierID.setText(searchedSupplier.getSup_id());
                txtSupplierName.setText(searchedSupplier.getSup_name());
                txtSupplierTele.setText(searchedSupplier.getTel_no());
                txtSupplierNIC.setText((searchedSupplier.getNic()));
                txtCompanyName.setText(searchedSupplier.getCompany_name());
                txtCompanyAddress.setText(searchedSupplier.getCompany_address());
            } catch (Exception ex) {
                Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_cmbSupplierItemStateChanged

    private void lblSupplierOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierOrdersMouseEntered
        lblSupplierOrders.setSize(175, 55);
    }//GEN-LAST:event_lblSupplierOrdersMouseEntered

    private void lblSupplierOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierOrdersMouseExited
        lblSupplierOrders.setSize(170, 50);
    }//GEN-LAST:event_lblSupplierOrdersMouseExited

    private void lblSupplierPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierPaymentMouseEntered
        lblSupplierPayment.setSize(205, 55);
    }//GEN-LAST:event_lblSupplierPaymentMouseEntered

    private void lblSupplierPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierPaymentMouseExited
        lblSupplierPayment.setSize(200, 50);
    }//GEN-LAST:event_lblSupplierPaymentMouseExited

    private void lblSupplierOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierOrdersMouseClicked
        SupplierOrderPanel orderPanel = new SupplierOrderPanel();
        JPanel panel = HomePage.getMainPanel();
        panel.removeAll();
        orderPanel.setSize(panel.getSize());
        panel.add(orderPanel);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_lblSupplierOrdersMouseClicked

    private void lblSupplierPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierPaymentMouseClicked
        SupplierPaymentPanel paymentPanel = new SupplierPaymentPanel();
        JPanel panel = HomePage.getMainPanel();
        panel.removeAll();
        paymentPanel.setSize(panel.getSize());
        panel.add(paymentPanel);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_lblSupplierPaymentMouseClicked

    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNameActionPerformed
        if(Validation.name(txtSupplierName)){
            txtSupplierTele.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Name");
                    
        }
    }//GEN-LAST:event_txtSupplierNameActionPerformed

    private void txtSupplierTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierTeleActionPerformed
        if(Validation.phoneNumber(txtSupplierTele)){
           txtSupplierNIC.requestFocus();
       }else{
           JOptionPane.showMessageDialog(this,"Invalid Phone Number");
       }
    }//GEN-LAST:event_txtSupplierTeleActionPerformed

    private void txtSupplierNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNICActionPerformed
        if(Validation.nicValidation(txtSupplierNIC)){
            txtCompanyName.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this,"Invalid NIC");
        }
    }//GEN-LAST:event_txtSupplierNICActionPerformed

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        if(Validation.name(txtCompanyName)){
            txtCompanyAddress.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Name");           
        }
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void txtCompanyAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyAddressActionPerformed
        
    }//GEN-LAST:event_txtCompanyAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnID;
    private javax.swing.JButton btnName;
    private javax.swing.JButton btnNewItemCategory1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblSupplierOrders;
    private javax.swing.JLabel lblSupplierPayment;
    private javax.swing.JScrollPane scrTbl;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtCompanyAddress;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCurrentSupplier;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtSupplierNIC;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierTele;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        loadAllSuppliers();
    }

    private void loadAllSuppliers() {
        DefaultTableModel dtm = (DefaultTableModel) tblSupplier.getModel();
        dtm.setRowCount(0);

        try {
            List<SupplierDTO> suppliers = ManageSupplierController.getAllSuppliers();

            if (suppliers != null) {
                for (SupplierDTO supplier : suppliers) {
                    Object[] rowData = {
                        supplier.getSup_id(),
                        supplier.getSup_name(),
                        supplier.getTel_no(),
                        supplier.getNic(),
                        supplier.getCompany_name(),
                        supplier.getCompany_address()
                    };
                    dtm.addRow(rowData);
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearAllTextFields() {
        txtSupplierID.setText("");
        txtSupplierName.setText("");
        txtSupplierTele.setText("");
        txtSupplierNIC.setText("");
        txtCompanyName.setText("");
        txtCompanyAddress.setText("");
    }

}
