/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.LOOPER_gentsWear.view_panel;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import lk.ijse.LOOPER_gentsWear.controller.ManageItemController;
import lk.ijse.LOOPER_gentsWear.controller.ManageSupplierController;
import lk.ijse.LOOPER_gentsWear.dto.ItemDTO;
import lk.ijse.LOOPER_gentsWear.dto.SupplierDTO;
import lk.ijse.LOOPER_gentsWear.view.HomePage;
import lk.ijse.LOOPER_gentsWear.view.POS_Main_Cashier;


/**
 *
 * @author Sandun_CJ
 */
public class SupplierReturnPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public SupplierReturnPanel() {
        initComponents();
        loadAllSuppliers();
        loadAllItemCodes();
        setDate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtReturnID = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReturn = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtReson = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtSubAmout = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtDate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        cmbItemCode = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 3));
        setPreferredSize(new java.awt.Dimension(1070, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/return.png"))); // NOI18N
        jLabel2.setText("Supplier's Return..");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 50));

        txtReturnID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtReturnID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReturnID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtReturnID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 90, 30));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Return ID");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 74, 30));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Quantity");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 74, 30));

        txtQty.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, 30));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Supplier");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 80, 30));

        cmbSupplier.setEditable(true);
        cmbSupplier.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(cmbSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 100, 30));

        txtUnitPrice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUnitPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnitPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 90, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Unit Price");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 74, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Amount");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 74, 30));

        txtAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 90, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Item Code");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 80, 30));

        tblReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Return ID", "Supplier", "Invoice No", "Item Code", "Description", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblReturn);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 1020, 240));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Reason");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 74, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Description");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 80, 30));

        txtDescription.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDescription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 110, 30));

        txtReson.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtReson.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtReson, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 330, 30));

        btnSave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/FontAwesome_f02f(0)_32.png"))); // NOI18N
        btnSave.setText("Save & Print");
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 510, 150, 30));

        txtSubAmout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSubAmout.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubAmout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtSubAmout, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 110, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Sub Amount");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 80, 30));

        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/Entypo_e70c(0)_32.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setToolTipText("Add details to table");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 100, 30));

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 110, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Date");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 40, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/back-button.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 60, 60));

        cmbItemCode.setEditable(true);
        cmbItemCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbItemCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemCodeItemStateChanged(evt);
            }
        });
        add(cmbItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        HomePanel homePanel=new HomePanel();
        JPanel panel=HomePage.getMainPanel();
        panel.removeAll();
        homePanel.setSize(panel.getSize());
        panel.add(homePanel);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setSize(65,65);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setSize(60,60);
    }//GEN-LAST:event_btnBackMouseExited

    private void cmbItemCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemCodeItemStateChanged
        if (cmbItemCode.getSelectedIndex() != -1) {
            try {
                ItemDTO searchItem = ManageItemController.searchItem(cmbItemCode.getSelectedItem().toString());
                txtDescription.setText(searchItem.getDescription());                
            } catch (Exception ex) {
                Logger.getLogger(SupplierReturnPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmbItemCodeItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbItemCode;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblReturn;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtReson;
    private javax.swing.JTextField txtReturnID;
    private javax.swing.JTextField txtSubAmout;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables

    private void loadAllSuppliers() {
        try {
            List<SupplierDTO> supplier = ManageSupplierController.getAllSuppliers();
            if (supplier != null) {
                for (SupplierDTO supplierDTO : supplier) {
                    cmbSupplier.addItem(supplierDTO.getSup_id());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(SupplierReturnPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllItemCodes() {
        try {
            List<ItemDTO> item = ManageItemController.getAllItems();
            if(item !=null){
                for (ItemDTO itemDTO : item) {
                    cmbItemCode.addItem(itemDTO.getiCode());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(SupplierReturnPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("E dd-MM-yyyy");
        txtDate.setText(s.format(d));
    }
}
