/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.LOOPER_gentsWear.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.border.LineBorder;
import lk.ijse.LOOPER_gentsWear.view_panel.GRNPanel;
import lk.ijse.LOOPER_gentsWear.view_panel.HomePanel;
import lk.ijse.LOOPER_gentsWear.view_panel.ItemPanel;
import lk.ijse.LOOPER_gentsWear.view_panel.ReportPanel;
import lk.ijse.LOOPER_gentsWear.view_panel.SettingPanel;
import lk.ijse.LOOPER_gentsWear.view_panel.SupplierPanel;

/**
 *
 * @author Sandun_CJ
 */
public class HomePage extends javax.swing.JFrame {
    private static JFrame homeFrame;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        homeFrame=this;
        labelVisibleFalse();
        setLocationRelativeTo(null);
        loadHomePanel();
        setDate();
        setTime();

    }
    public static JFrame getFrame(){
        return homeFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblItem = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblGrn = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        lblSetting = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 760));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblItem.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/item.png"))); // NOI18N
        lblItem.setText("ITEM");
        lblItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        lblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblItemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblItemMousePressed(evt);
            }
        });
        jPanel1.add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 170, 50));

        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/Minimize1.png"))); // NOI18N
        lblMinimize.setToolTipText("Minimize");
        lblMinimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 50, 32));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/close2 (2).png"))); // NOI18N
        lblClose.setToolTipText("Close");
        lblClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 50, 32));

        lblLogout.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/logout.png"))); // NOI18N
        lblLogout.setText("LOGOUT");
        lblLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLogoutMousePressed(evt);
            }
        });
        jPanel1.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 170, 50));

        lblHome.setDisplayedMnemonic('H');
        lblHome.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/home.png"))); // NOI18N
        lblHome.setText("HOME");
        lblHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblHomeMouseReleased(evt);
            }
        });
        jPanel1.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 170, 50));

        lblGrn.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblGrn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/grn.png"))); // NOI18N
        lblGrn.setText("GRN");
        lblGrn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        lblGrn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGrnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGrnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGrnMouseExited(evt);
            }
        });
        jPanel1.add(lblGrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 170, 50));

        lblSupplier.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/supplier.png"))); // NOI18N
        lblSupplier.setText("SUPPLIER");
        lblSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        lblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupplierMouseExited(evt);
            }
        });
        jPanel1.add(lblSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 170, 50));

        lblReport.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/report.png"))); // NOI18N
        lblReport.setText("REPORT");
        lblReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportMouseExited(evt);
            }
        });
        jPanel1.add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 170, 50));

        lblSetting.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/setting.png"))); // NOI18N
        lblSetting.setText("SETTINGS");
        lblSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        lblSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSettingMouseExited(evt);
            }
        });
        jPanel1.add(lblSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 170, 50));

        a.setBackground(new java.awt.Color(0, 102, 255));
        a.setOpaque(true);
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 30, 50));

        b.setBackground(new java.awt.Color(0, 102, 255));
        b.setOpaque(true);
        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 30, 50));

        c.setBackground(new java.awt.Color(0, 102, 255));
        c.setOpaque(true);
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 30, 50));

        d.setBackground(new java.awt.Color(0, 102, 255));
        d.setOpaque(true);
        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 30, 50));

        e.setBackground(new java.awt.Color(0, 102, 255));
        e.setOpaque(true);
        jPanel1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 30, 50));

        f.setBackground(new java.awt.Color(0, 102, 255));
        f.setOpaque(true);
        jPanel1.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 30, 50));

        g.setBackground(new java.awt.Color(0, 102, 255));
        g.setOpaque(true);
        jPanel1.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 30, 50));

        lblTime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("Time");
        lblTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 100, 20));

        lblDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Date");
        lblDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 20));

        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 3));
        panelMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMain.setOpaque(false);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1064, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        jPanel1.add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 1070, 570));

        lblDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        jPanel1.add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 220, 570));
        lblDashboard.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/newlogo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 120, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("LOOPER GentsWear,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 230, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("No: 217/B, Dickson Rd, Galle.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 240, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("Tel : 0914489971");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 170, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("E-mail : looperGents@gmail.com");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 250, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemMouseClicked
        a.setVisible(false);
        b.setVisible(true);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        
        panelMain.removeAll();
        ItemPanel itemPanel = new ItemPanel();
        itemPanel.setVisible(true);
        itemPanel.setSize(panelMain.getSize());
        panelMain.add(itemPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_lblItemMouseClicked

    private void lblItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemMousePressed

    }//GEN-LAST:event_lblItemMousePressed

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setBorder(new LineBorder(new Color(0, 102, 255), 2));
        lblHome.setForeground(new Color(0, 102, 255));
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setBorder(new LineBorder(new Color(204, 204, 255), 2));
        lblHome.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        a.setVisible(true);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        
        panelMain.removeAll();
        
        HomePanel homePanel = new HomePanel();
        homePanel.setVisible(true);
        homePanel.setSize(panelMain.getSize());
        panelMain.add(homePanel);
        panelMain.repaint();
        panelMain.revalidate();
        
        
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseReleased

    }//GEN-LAST:event_lblHomeMouseReleased

    private void lblItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemMouseEntered
        lblItem.setBorder(new LineBorder(new Color(0, 102, 255), 2));
        lblItem.setForeground(new Color(0, 102, 255));
    }//GEN-LAST:event_lblItemMouseEntered

    private void lblItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemMouseExited
        lblItem.setBorder(new LineBorder(new Color(204, 204, 255), 2));
        lblItem.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblItemMouseExited

    private void lblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseClicked
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(true);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        
        panelMain.removeAll();
        SupplierPanel supplierPanel = new SupplierPanel();
        supplierPanel.setVisible(true);
        supplierPanel.setSize(panelMain.getSize());
        panelMain.add(supplierPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_lblSupplierMouseClicked

    private void lblSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseEntered
        lblSupplier.setBorder(new LineBorder(new Color(0, 102, 255), 2));
        lblSupplier.setForeground(new Color(0, 102, 255));
    }//GEN-LAST:event_lblSupplierMouseEntered

    private void lblSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseExited
        lblSupplier.setBorder(new LineBorder(new Color(204, 204, 255), 2));
        lblSupplier.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSupplierMouseExited

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(true);
        f.setVisible(false);
        g.setVisible(false);
        
        panelMain.removeAll();
        ReportPanel reportPanel = new ReportPanel();
        reportPanel.setVisible(true);
        reportPanel.setSize(panelMain.getSize());
        panelMain.add(reportPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_lblReportMouseClicked

    private void lblReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseEntered
        lblReport.setBorder(new LineBorder(new Color(0, 102, 255), 2));
        lblReport.setForeground(new Color(0, 102, 255));
    }//GEN-LAST:event_lblReportMouseEntered

    private void lblReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseExited
        lblReport.setBorder(new LineBorder(new Color(204, 204, 255), 2));
        lblReport.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblReportMouseExited

    private void lblGrnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrnMouseClicked
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(true);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        
        panelMain.removeAll();
        GRNPanel gRNPanel = new GRNPanel();
        gRNPanel.setVisible(true);
        gRNPanel.setSize(panelMain.getSize());
        panelMain.add(gRNPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_lblGrnMouseClicked

    private void lblGrnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrnMouseEntered
        lblGrn.setBorder(new LineBorder(new Color(0, 102, 255), 2));
        lblGrn.setForeground(new Color(0, 102, 255));
    }//GEN-LAST:event_lblGrnMouseEntered

    private void lblGrnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrnMouseExited
        lblGrn.setBorder(new LineBorder(new Color(204, 204, 255), 2));
        lblGrn.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblGrnMouseExited

    private void lblSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseClicked
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(true);
        g.setVisible(false);
        
        panelMain.removeAll();
        SettingPanel settingPanel = new SettingPanel();
        settingPanel.setVisible(true);
        settingPanel.setSize(panelMain.getSize());
        panelMain.add(settingPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_lblSettingMouseClicked

    private void lblSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseEntered
        lblSetting.setBorder(new LineBorder(new Color(0, 102, 255), 2));
        lblSetting.setForeground(new Color(0, 102, 255));
    }//GEN-LAST:event_lblSettingMouseEntered

    private void lblSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseExited
        lblSetting.setBorder(new LineBorder(new Color(204, 204, 255), 2));
        lblSetting.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSettingMouseExited

    private void lblLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMousePressed

    }//GEN-LAST:event_lblLogoutMousePressed

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setBorder(new LineBorder(new Color(204, 204, 255), 2));
        lblLogout.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setBorder(new LineBorder(new Color(0, 102, 255), 2));
        lblLogout.setForeground(new Color(0, 102, 255));
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        setExtendedState(HomePage.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setBorder(new LineBorder(Color.red));
        lblMinimize.setIcon(new ImageIcon("./src/lk/ijse/LOOPER_gentsWear/images/Minimize2.png"));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setBorder(new LineBorder(Color.black));
        lblMinimize.setIcon(new ImageIcon("./src/lk/ijse/LOOPER_gentsWear/images/Minimize1.png"));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setBorder(new LineBorder(Color.red));
        lblClose.setIcon(new ImageIcon("./src/lk/ijse/LOOPER_gentsWear/images/close1.png"));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setBorder(new LineBorder(Color.black));
        lblClose.setIcon(new ImageIcon("./src/lk/ijse/LOOPER_gentsWear/images/close2(2).png"));
    }//GEN-LAST:event_lblCloseMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JLabel f;
    private javax.swing.JLabel g;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGrn;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblSetting;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTime;
    private static javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables

    private void labelVisibleFalse() {
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
    }

    public static JPanel getMainPanel() {
        return panelMain;
    }
    
    private void loadHomePanel() {
        panelMain.removeAll();
        HomePanel homePanel = new HomePanel();
        homePanel.setVisible(true);
        homePanel.setSize(panelMain.getSize());
        panelMain.add(homePanel);
        panelMain.repaint();
        panelMain.revalidate();
        a.setVisible(true);
    }

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("E dd-MM-yyyy");
        lblDate.setText(s.format(d));
    }

    private void setTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                lblTime.setText(s.format(d));
            }
        }).start();
    }
}
