/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.LOOPER_gentsWear.view;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import lk.ijse.LOOPER_gentsWear.common.Validation;
import lk.ijse.LOOPER_gentsWear.controller.ManageCashierController;
import lk.ijse.LOOPER_gentsWear.controller.ManageItemController;
import lk.ijse.LOOPER_gentsWear.controller.ManagePaymentController;
import lk.ijse.LOOPER_gentsWear.controller.ManagePlaceOrderController;
import lk.ijse.LOOPER_gentsWear.controller.ReportController;
import lk.ijse.LOOPER_gentsWear.dto.CashierDTO;
import lk.ijse.LOOPER_gentsWear.dto.ItemDTO;
import lk.ijse.LOOPER_gentsWear.dto.OrderDTO;
import lk.ijse.LOOPER_gentsWear.dto.OrderDetailsDTO;
import lk.ijse.LOOPER_gentsWear.dto.PaymentDTO;
import lk.ijse.LOOPER_gentsWear.observer.Observer;
import lk.ijse.LOOPER_gentsWear.service.custom.ItemService;
import lk.ijse.LOOPER_gentsWear.view_panel.AllOrdersPanel;
import lk.ijse.LOOPER_gentsWear.view_panel.GRNPanel;
import lk.ijse.jasper.IJSEJasperViewer;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author Sandun_CJ
 */
public class POS_Main_Cashier extends javax.swing.JFrame implements Observer {

    DefaultTableModel dtm;
    private static JFrame homeFrame;
    private static int userId;

    /**
     * Creates new form POS_Main
     */
    public POS_Main_Cashier() {

        initComponents();
        txtInvoiceNo.requestFocusInWindow();
        homeFrame = this;
        setDate();
        setTime();
        loadAllDressCode();
        dtm = (DefaultTableModel) tblOrder.getModel();
        txtTotItem.setText(Integer.toString(tblOrder.getRowCount()));

        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageItemController.getSubject().registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(POS_Main_Cashier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static JFrame getFrame() {
        return homeFrame;
    }

    public POS_Main_Cashier(String id) throws Exception {
        this();
        CashierDTO searchCashier = ManageCashierController.searchCashier(id);
        txtUserID.setText(searchCashier.getC_id() + "");
        txtLoggedName.setText(searchCashier.getC_name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtLoggedName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        cmbDressCode = new javax.swing.JComboBox<>();
        txtInvoiceNo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtQuantityOnHand = new javax.swing.JTextField();
        btnAddTable = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblClose = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTotItem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtChange = new javax.swing.JTextField();
        txtG_Amount = new javax.swing.JTextField();
        txtCash = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sales Transaction");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 410, 30));

        jLabel9.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 1010, 30));

        jLabel5.setBackground(new java.awt.Color(0, 102, 255));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 300, 40));

        jLabel23.setBackground(new java.awt.Color(0, 102, 255));
        jLabel23.setOpaque(true);
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 10, 680));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Cash Drawer Allocated  :  ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, 20));

        txtLoggedName.setEditable(false);
        txtLoggedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoggedNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoggedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("Logged on User  : ");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 20));

        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("01");
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 50, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setText("Cash Drawer ID :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 20));

        lblTime.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("Time");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 100, 20));

        lblDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Date");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 20));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/asset/logo1.png"))); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 320));

        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/asset/Minimize1.png"))); // NOI18N
        lblMinimize.setToolTipText("Minimize");
        lblMinimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 50, 32));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setText("Logged User_ID  : ");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 20));

        txtUserID.setEditable(false);
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Invoice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 310, 470));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Price");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Description");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 30));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        jPanel2.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 120, 30));

        cmbDressCode.setEditable(true);
        cmbDressCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbDressCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDressCodeItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbDressCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, 30));
        jPanel2.add(txtInvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Dress Code");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 30));

        txtPrice.setEditable(false);
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, 30));

        txtDescription.setEditable(false);
        jPanel2.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 160, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Invoice No ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, 30));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Qty on Hand");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 80, 30));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setText("Quantity ");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, 30));

        txtQuantityOnHand.setEditable(false);
        jPanel2.add(txtQuantityOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 120, 30));

        btnAddTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/asset/Entypo_e70c(0)_32.png"))); // NOI18N
        btnAddTable.setText("Add to Table");
        btnAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTableActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 260, 50));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setText("Amount");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, 30));

        txtAmount.setEditable(false);
        jPanel2.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 330, 530));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/asset/close2 (2).png"))); // NOI18N
        lblClose.setToolTipText("Close");
        lblClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 50, 32));

        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "LOoPER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 280, 210));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dress Code", "Description", "Unit Price", "Quantity", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder);
        if (tblOrder.getColumnModel().getColumnCount() > 0) {
            tblOrder.getColumnModel().getColumn(0).setResizable(false);
            tblOrder.getColumnModel().getColumn(1).setResizable(false);
            tblOrder.getColumnModel().getColumn(2).setResizable(false);
            tblOrder.getColumnModel().getColumn(3).setResizable(false);
            tblOrder.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, -2, 660, 390));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Total Items");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 70, 20));

        txtTotItem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtTotItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(txtTotItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 50, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Change");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 90, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Gross Amount");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Cash");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 90, 30));

        txtChange.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtChange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChangeActionPerformed(evt);
            }
        });
        jPanel3.add(txtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 140, 30));

        txtG_Amount.setBackground(new java.awt.Color(0, 0, 0));
        txtG_Amount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtG_Amount.setForeground(new java.awt.Color(0, 153, 0));
        txtG_Amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtG_Amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.add(txtG_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 140, 30));

        txtCash.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });
        jPanel3.add(txtCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 140, 30));

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/asset/FontAwesome_f02f(0)_32.png"))); // NOI18N
        btnSave.setText("Save & Print Bill");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 250, 40));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Remove Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 150, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 690, 610));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/change.png"))); // NOI18N
        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 40));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("All Orders");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 140, 40));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/LOOPER_gentsWear/images/logout.png"))); // NOI18N
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 280, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        setExtendedState(POS_Main_Cashier.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setBorder(new LineBorder(Color.red));
        lblMinimize.setIcon(new ImageIcon("./src/lk/ijse/LOOPER_gentsWear/asset/Minimize2.png"));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setBorder(new LineBorder(Color.black));
        lblMinimize.setIcon(new ImageIcon("./src/lk/ijse/LOOPER_gentsWear/asset/Minimize1.png"));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setBorder(new LineBorder(Color.red));
        lblClose.setIcon(new ImageIcon("./src/lk/ijse/LOOPER_gentsWear/asset/close1.png"));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setBorder(new LineBorder(Color.black));
        lblClose.setIcon(new ImageIcon("./src/lk/ijse/LOOPER_gentsWear/asset/close2(2).png"));
    }//GEN-LAST:event_lblCloseMouseExited

    private void cmbDressCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDressCodeItemStateChanged

        if (cmbDressCode.getSelectedIndex() != -1) {
            try {
                ItemDTO searchItem = ManageItemController.searchItem(cmbDressCode.getSelectedItem().toString());
                txtDescription.setText(searchItem.getDescription());
                txtQuantityOnHand.setText(Integer.toString(searchItem.getQty()));
                txtPrice.setText(Double.toString(searchItem.getSellingPrice()));

            } catch (Exception ex) {
                Logger.getLogger(POS_Main_Cashier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmbDressCodeItemStateChanged

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        ManageItemController itemController = new ManageItemController();
        ManagePaymentController paymentController = new ManagePaymentController();
        ManagePlaceOrderController placeOrderController = new ManagePlaceOrderController();

        if (cmbDressCode.getSelectedIndex() != -1) {
            try {

                OrderDTO orderDTO = new OrderDTO();
                orderDTO.setoID(Integer.parseInt(txtInvoiceNo.getText()));
                orderDTO.setoDate(lblDate.getText());
                orderDTO.setoTime(lblTime.getText());
                orderDTO.setAmount(Double.parseDouble(txtAmount.getText()));

                PaymentDTO paymentDTO = new PaymentDTO();
                paymentDTO.setGrossAmount(Double.parseDouble(txtG_Amount.getText()));
                paymentDTO.setCash(Double.parseDouble(txtCash.getText()));
                paymentDTO.setBalance(Double.parseDouble(txtChange.getText()));

                orderDTO.setPaymentDTO(paymentDTO);

                List<OrderDetailsDTO> list = new ArrayList<>();
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    ItemDTO searchItem = itemController.searchItem((String) dtm.getValueAt(i, 0));
                    searchItem.setQty(searchItem.getQty() - Integer.parseInt(dtm.getValueAt(i, 3).toString()));

                    OrderDetailsDTO detailsDTO = new OrderDetailsDTO();
                    detailsDTO.setItemDTO(searchItem);
                    detailsDTO.setOrderDTO(orderDTO);

                    list.add(detailsDTO);
                }
                orderDTO.setList(list);
                boolean addOrder = placeOrderController.addOrder(orderDTO);

                if (addOrder) {
                    JOptionPane.showMessageDialog(rootPane, "Added");
                    clearAlltextField();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Failed");
                }

            } catch (Exception ex) {
                Logger.getLogger(POS_Main_Cashier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        PrintBill();
        clearAlltextField();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed

        if (Validation.numberOnly(txtQuantity)) {
            int x = Integer.parseInt(txtQuantity.getText());
            int qtyOnhand = Integer.parseInt(txtQuantityOnHand.getText()) - x;
            if (qtyOnhand >= 0) {
                txtQuantityOnHand.setText(Integer.toString(qtyOnhand));
                Double amount = x * Double.parseDouble(txtPrice.getText());
                if (cmbDressCode.getSelectedIndex() == -1) {
                    JOptionPane.showMessageDialog(null, "Item is not Selected");
                } else {

                    if (getDuplicateRow(cmbDressCode.getSelectedItem()) != -1) {
                        DefaultTableModel dtm = (DefaultTableModel) tblOrder.getModel();
                        int row = getDuplicateRow(cmbDressCode.getSelectedItem());
                        int newQty = (Integer.parseInt(dtm.getValueAt(row, 3).toString()) + Integer.parseInt(txtQuantity.getText()));
                        dtm.setValueAt(newQty, row, 3);
                        dtm.setValueAt((double) newQty * Double.parseDouble(txtPrice.getText()), row, 4);
                        setAmount();
                    } else {
                        Object[] rowData = {cmbDressCode.getSelectedItem(), txtDescription.getText(), txtPrice.getText(), x, amount};
                        dtm.addRow(rowData);
                        txtAmount.setText(Double.toString(amount));
                        txtTotItem.setText(Integer.toString(tblOrder.getRowCount()));
                        setAmount();
                    }
                    txtQuantity.setText("");
                    cmbDressCode.requestFocusInWindow();

                }
            } else {
                JOptionPane.showMessageDialog(null, "Items are not Available");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Input");
        }


    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnAddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTableActionPerformed
        int x = Integer.parseInt(txtQuantity.getText());
        int qtyOnhand = Integer.parseInt(txtQuantityOnHand.getText()) - x;
        if (qtyOnhand >= 0) {
            txtQuantityOnHand.setText(Integer.toString(qtyOnhand));
            Double amount = x * Double.parseDouble(txtPrice.getText());
            if (cmbDressCode.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Item is not Selected");
            } else {
                Object[] rowData = {cmbDressCode.getSelectedItem(), txtDescription.getText(), txtPrice.getText(), x, amount};
                dtm.addRow(rowData);
                txtAmount.setText(Double.toString(amount));
                setAmount();
                txtTotItem.setText(Integer.toString(tblOrder.getRowCount()));

                txtQuantity.setText("");
                txtQuantityOnHand.setText("");
                txtPrice.setText("");
                txtDescription.setText("");

                cmbDressCode.requestFocusInWindow();

            }
        } else {
            JOptionPane.showMessageDialog(null, "Items are not Available");
        }
    }//GEN-LAST:event_btnAddTableActionPerformed

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        if (Validation.priceText(txtCash)) {
            selBalance();
            txtChange.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Input");
        }

    }//GEN-LAST:event_txtCashActionPerformed

    private void txtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChangeActionPerformed
        if (Validation.priceText(txtChange)) {
            btnSave.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Input");
        }
    }//GEN-LAST:event_txtChangeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dtm.removeRow(tblOrder.getSelectedRow());
        setAmount();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AllOrdersPanel allOrdersPanel = new AllOrdersPanel(POS_Main_Cashier.getFrame(), true);
        allOrdersPanel.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed

    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "You are LogOut");
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtLoggedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoggedNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoggedNameActionPerformed

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS_Main_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS_Main_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS_Main_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS_Main_Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS_Main_Cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTable;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbDressCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtG_Amount;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JTextField txtLoggedName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtQuantityOnHand;
    private javax.swing.JTextField txtTotItem;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("E dd-MM-yyyy");
        lblDate.setText(s.format(d));

    }

    private void setTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                lblTime.setText(s.format(d));
            }
        }).start();
    }

    private void loadAllDressCode() {

        cmbDressCode.removeAllItems();
        try {
            List<ItemDTO> all = ManageItemController.getAllItems();
            if (all != null) {
                for (ItemDTO itemDTO : all) {
                    cmbDressCode.addItem(itemDTO.getiCode());
                }

            }
        } catch (Exception ex) {
            Logger.getLogger(POS_Main_Cashier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setAmount() {
        double total = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            total += Double.parseDouble(dtm.getValueAt(i, 4).toString());
        }
        txtG_Amount.setText(Double.toString(total));
    }

    private void selBalance() {
        double balnce = Double.parseDouble(txtCash.getText()) - Double.parseDouble(txtG_Amount.getText());
        txtChange.setText(Double.toString(balnce));
    }

    private void clearAlltextField() {
        txtInvoiceNo.setText("");
        txtDescription.setText("");
        txtPrice.setText("");
        cmbDressCode.setSelectedItem("Dresses");
        txtQuantity.setText("");
        txtQuantityOnHand.setText("");
        txtG_Amount.setText("");
        dtm.setRowCount(0);
        txtCash.setText("");
        txtChange.setText("");
        txtAmount.setText("");
        txtTotItem.setText("");

    }

    private int getDuplicateRow(Object selectedItem) {
        DefaultTableModel dtm = (DefaultTableModel) tblOrder.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (dtm.getValueAt(i, 0).equals(selectedItem)) {
                return i;
            }
        }
        return -1;
    }

    @Override
    public void updateObservers() throws Exception {
        loadAllDressCode();
    }

    /**
     * @return the userId
     */
    public static int getUserId() {
        return userId;
    }

    /**
     * @param aUserId the userId to set
     */
    public static void setUserId(int aUserId) {
        userId = aUserId;
    }

    private void PrintBill() {
        try {
            JasperPrint filledReport = ReportController.getInvoiceReports();
            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
            frmJasperViewer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frmJasperViewer.setTitle("Print Bill");
            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            frmJasperViewer.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(POS_Main_Cashier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
